name: CI
run-name: ${{ github.actor }} is learning GitHub Actions

on: [push, pull_request]

jobs:
  test:
    # virtual environments: https://github.com/actions/virtual-environments
    runs-on: ubuntu-22.04

    steps:
      # Caches and restores the bazelisk download directory.
      - name: Cache bazel and bazelisk
        uses: actions/cache@v3
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}

      - uses: actions/checkout@v3

      # build
      - name: bazel build
        run: bazel build //...
